#! /usr/bin/env bash

. "$WMC";

for w in $(lsw; lsw -u); do
  chwb -s $border_width $w;
  if (( w == $(pfw) )); then
    chwb -c $border_color_focus $w;
  else
    chwb -c $border_color_normal $w;
  fi
done
