#! /usr/bin/env dash

# WM client

. $UTIL;

dir="$WMtmp/clients";
mkdir -p $dir;
mapped="$dir/mapped";
[ ! -f $mapped ] && lsw >$mapped;
pointerf="$dir/pointer";
if [ ! -f $pointerf ]; then
  pointer=$(length $mapped);
  echo $pointer > $pointerf;
else
  read pointer <$pointerf
  log "pointerf: $pointer";
fi

bye() {
  sed "$pointer p;d" $mapped;
  echo $pointer > $pointerf;
  [ $# -gt 0 ] && exit $1;
}

client_add() {
  echo $1 >> $mapped;
}
client_remove() {
  tmp=$(mktemp $mapped.XXXXX);
  grep -v $1 < $mapped > $tmp;
  mv $tmp $mapped;
}

client_next() {
  amt=${1:-1};
  pointer=$(( pointer + $amt ));
  log $pointer;
  if [ $pointer -gt $(length $mapped) ]; then
    pointer=$(( pointer - $(length $mapped) ));
  fi
  bye;
}
client_prev() {
  amt=${1:-1};
  pointer=$(( pointer - $amt ));
  log $pointer;
  if [ $pointer -lt 1 ]; then
    pointer=$(( pointer + $(length $mapped) ));
  fi
  bye;
}

main() {
  cmd="$1"; shift;
  case "$cmd" in
    next)
      client_next $@;
      ;;
    prev)
      client_prev $@;
      ;;
    pointer)
      echo;
      ;;
    *) die $E_ARG "Unknown arg: $@" ;;
  esac
}

main $@
