#! /usr/bin/env bash

# WM FOCUS

. $UTIL

focus_wid() {
    if wattr "$1"; then
      wtf "$1";
      chwso -r "$1";
      wm apply_borders;
    fi
    wm hist push $1;
}

case "$1" in
  next)
    wid=$(lsw | grep -v $(pfw) | sed '1 p;d');
    # wid=$(wm hist newer)
    ;;
  prev)
    wid=$(lsw | grep -v $(pfw) | sed '$ p;d');
    # wid=$(wm hist older)
    ;;
  0x*)
    wid=$1
    ;;
  *)
    cmd="$1"; shift;
    if [ -x "$WMscripts/$cmd" ]; then
      focus_wid $($WMscripts/$cmd $@);
    else
      die $E_EXE "Unknown command: \"$cmd\"";
    fi
    ;;
esac

focus_wid $wid;
